title: Contributions

description: >-
  attributed to anticrisis

description_2: >-

logo: "/assets/images/tracer_icon.png"
baseurl: ""

author: "Anticrisis"
bio: >-
  "Be kind whenever possible. It is always possible."
  -- Dalai Lama
  <br>
  "The true sign of intelligence is not knowledge but imagination."
  -- A. Einstein
author_image: "/assets/images/tracer_icon.png"
#twitter_username: ""
github_username: anticrisis

analytics_id: ""

markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  
paginate: 5
